name: run

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    python-version: [3.6, 3.7, 3.8, 3.9-dev, 3.10-dev]
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: deadsnakes/action@v3.0.1
        with:
          python-version: "3.6"
      - run: python --version --version && which python


